In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("data.csv")

In [6]:
df.isnull().sum()

transaction_id        0
transaction_time      0
transaction_amount    0
location              0
device_type           0
channel               0
card_present          0
customer_age          0
merchant_category     0
is_fraud              0
dtype: int64

In [7]:
df['channel'].unique()

array(['Online', 'POS'], dtype=object)

In [8]:
df['device_type'].unique()

array(['POS', 'Tablet', 'Mobile', 'Desktop'], dtype=object)

In [9]:
df['location'].unique()

array(['Delhi', 'Chennai', 'Hyderabad', 'Bangalore', 'Kolkata', 'Mumbai'],
      dtype=object)

In [10]:
df['card_present'].unique()

array(['No', 'Yes'], dtype=object)

In [11]:
df['merchant_category'].unique()

array(['Electronics', 'Food', 'Travel', 'Clothing', 'Grocery',
       'Entertainment'], dtype=object)

In [12]:
df=df.drop(['transaction_id'],axis=1)

In [13]:
df.head()

,transaction_time,transaction_amount,location,device_type,channel,card_present,customer_age,merchant_category,is_fraud
0,6,1728.21,Delhi,POS,Online,No,55,Electronics,0
1,19,2528.32,Chennai,POS,Online,Yes,21,Electronics,0
2,14,114.93,Hyderabad,Tablet,POS,Yes,50,Food,0
3,10,526.77,Bangalore,POS,POS,Yes,44,Travel,0
4,7,895.75,Bangalore,POS,Online,Yes,52,Clothing,0

In [14]:
df['device_type']=df['device_type'].str.lower()
df['card_present']=df['card_present'].str.lower()
df['channel']=df['channel'].str.lower()
df['merchant_category']=df['merchant_category'].str.lower()

In [15]:
df.head()

,transaction_time,transaction_amount,location,device_type,channel,card_present,customer_age,merchant_category,is_fraud
0,6,1728.21,Delhi,pos,online,no,55,electronics,0
1,19,2528.32,Chennai,pos,online,yes,21,electronics,0
2,14,114.93,Hyderabad,tablet,pos,yes,50,food,0
3,10,526.77,Bangalore,pos,pos,yes,44,travel,0
4,7,895.75,Bangalore,pos,online,yes,52,clothing,0

In [16]:
# Fix for card_present
df['card_present'] = df['card_present'].str.lower().map({"yes": 1, "no": 0})

# Fix for device_type
df['device_type'] = df['device_type'].str.lower().map({"pos": 0, "tablet": 1, "desktop": 2, "mobile": 3})

In [17]:
df.head()

,transaction_time,transaction_amount,location,device_type,channel,card_present,customer_age,merchant_category,is_fraud
0,6,1728.21,Delhi,0,online,0,55,electronics,0
1,19,2528.32,Chennai,0,online,1,21,electronics,0
2,14,114.93,Hyderabad,1,pos,1,50,food,0
3,10,526.77,Bangalore,0,pos,1,44,travel,0
4,7,895.75,Bangalore,0,online,1,52,clothing,0

In [18]:
df=df.drop(['location'],axis=1)

In [19]:
df.head()

,transaction_time,transaction_amount,device_type,channel,card_present,customer_age,merchant_category,is_fraud
0,6,1728.21,0,online,0,55,electronics,0
1,19,2528.32,0,online,1,21,electronics,0
2,14,114.93,1,pos,1,50,food,0
3,10,526.77,0,pos,1,44,travel,0
4,7,895.75,0,online,1,52,clothing,0

In [20]:
df['merchant_category'] = df['merchant_category'].str.lower().map({
    "grocery": 0,
    "electronics": 1,
    "clothing": 2,
    "travel": 3,
    "food": 4,
    "entertainment": 5
})

In [21]:
df['channel'] = df['channel'].str.lower().map({
    "pos": 0,
    "online": 1
})

In [22]:
df.head()

,transaction_time,transaction_amount,device_type,channel,card_present,customer_age,merchant_category,is_fraud
0,6,1728.21,0,1,0,55,1,0
1,19,2528.32,0,1,1,21,1,0
2,14,114.93,1,0,1,50,4,0
3,10,526.77,0,0,1,44,3,0
4,7,895.75,0,1,1,52,2,0

In [23]:
df.to_csv("cleaned_data.csv",index=False)

In [6]:
import pandas as pd
data=pd.read_csv("cleaned_data.csv")
data["merchant_category"].unique()

array([1, 4, 3, 2, 0, 5])